### ISSUE TITLE
pollboardactivity.js causes fatal api crash

### ISSUE THREAD

**Issue by Temetz** [N4SJAMK/teamboard-api#53]
```javascript
/app/node_modules/mongoose/lib/utils.js:413
        throw err;
              ^
TypeError: Cannot read property 'id' of undefined
    at Promise.<anonymous> (/app/utils/pollboardactivity.js:28:24)
    at Promise.<anonymous> (/app/node_modules/mongoose/node_modules/mpromise/lib/promise.js:172:8)
    at Promise.emit (events.js:107:17)
    at Promise.emit (/app/node_modules/mongoose/node_modules/mpromise/lib/promise.js:84:38)
    at Promise.reject (/app/node_modules/mongoose/node_modules/mpromise/lib/promise.js:111:15)
    at Promise.error (/app/node_modules/mongoose/lib/promise.js:89:15)
    at handleSave (/app/node_modules/mongoose/lib/model.js:125:17)
    at /app/node_modules/mongoose/lib/utils.js:408:16
    at /app/node_modules/mongoose/node_modules/mongodb/lib/mongodb/collection/core.js:572:7
    at /app/node_modules/mongoose/node_modules/mongodb/lib/mongodb/db.js:1131:7
```

**Comment by tanelih** [comment]
We don't actually call this in the latest client versions, but the code should probably be removed from the API just to make sure no one ever mistakes this for a feature.

**Comment by Temetz** [comment]
/setactivity was deprecated in https://github.com/N4SJAMK/teamboard-api/commit/c548a87836a891c3358f621c54d0d43b5a9d8102

This removes the issue.
